version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
    #   - aws --version
    #   - $(aws ecr get-login --no-include-email --region ap-south-1)
      - docker login --username $DOCKERHUB_USR --password $DOCKERHUB_PASS
      - REPOSITORY_URI=$BASEURL/scikiq_web
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --build-arg BUILD_ENV=$BUILD_ENV -t $REPOSITORY_URI:$BUILD_ENV-latest .
      - docker tag $REPOSITORY_URI:$BUILD_ENV-latest $REPOSITORY_URI:$BUILD_ENV-$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$BUILD_ENV-latest
      - docker push $REPOSITORY_URI:$BUILD_ENV-$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"scikiq-web","imageUri":"%s"}]' $REPOSITORY_URI:$BUILD_ENV-$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json