# Generated by Django 5.1.3 on 2024-11-06 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkqLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_code', models.CharField(max_length=45)),
                ('lookup_type', models.CharField(blank=True, max_length=45, null=True)),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('desc', models.CharField(blank=True, max_length=500, null=True)),
                ('key', models.CharField(max_length=45)),
                ('value1', models.CharField(blank=True, max_length=45, null=True)),
                ('value2', models.CharField(blank=True, max_length=500, null=True)),
                ('value3', models.CharField(blank=True, max_length=45, null=True)),
                ('value4', models.CharField(blank=True, max_length=45, null=True)),
                ('value5', models.CharField(blank=True, max_length=45, null=True)),
                ('client_id', models.IntegerField(default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_valid', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'skq_lookup',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=20, null=True)),
                ('alternate_contact_no', models.CharField(blank=True, max_length=20, null=True)),
                ('user_type', models.CharField(max_length=50)),
                ('user_category', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistrationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_data_types', models.TextField(blank=True, null=True)),
                ('purchase_frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('budget_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_data_formats', models.TextField(blank=True, null=True)),
                ('update_frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('notification_preferences', models.TextField(blank=True, null=True)),
                ('compliance_standards', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
